 /*
0	  5 Containers
1     5 Containers, 1 Spawn
2	  5 Containers, 1 Spawn , 5  Extensions (50 capacity) , Ramparts (50K max hits), Walls
3     5 Containers, 1 Spawn , 10 Extensions (50 capacity) , Ramparts (1M max hits), Walls, 1 Tower
4	  5 Containers, 1 Spawn , -5 Extensions (50 capacity) , Ramparts (3M max hits), Walls, 1 Tower, Storage
5	  5 Containers, 1 Spawn , 5 Extensions (50 capacity) , Ramparts (10M max hits), Walls, 2 Towers, Storage, 2 Links
6	  5 Containers, 1 Spawn , 40 Extensions (50 capacity) , Ramparts (5M max hits), Walls, 2 Towers, Storage, 3 Links, Extractor, 3 Labs, Terminal
7	  5 Containers, 2 Spawns, 50 Extensions (100 capacity), Ramparts (100M max hits), Walls, 3 Towers, Storage, 4 Links, Extractor, 6 Labs, Terminal
8	  5 Containers, 3 Spawns, 60 Extensions (-50 capacity), Ramparts (50M max hits), Walls, 6 Towers, Storage, 6 Links, Extractor, 10 Labs, Terminal, Observer, Power Spawn
*/
var buildings ={
 
   "buildings":{
      "storage":{
         "pos":[
            {
               "x":0,
               "y":0
            }
         ]
      },
      "spawn":{
         "pos":[
            {
               "x":2,
               "y":2
            },
            {
               "x":-1,
               "y":-2
            },
            {
               "x":0,
               "y":-2
            }
         ]
      },
      "tower":{
         "pos":[
            {
               "x":1,
               "y":0
            },
            {
               "x":2,
               "y":0
            },
            {
               "x":2,
               "y":1
            },
            {
               "x":0,
               "y":1
            },
            {
               "x":0,
               "y":2
            },
            {
               "x":1,
               "y":2
            }
         ]
      },
      "link":{
         "pos":[
            {
               "x":-1,
               "y":0
            }
         ]
      },
      "terminal":{
         "pos":[
            {
               "x":-2,
               "y":-1
            }
         ]
      },
      "lab":{
         "pos":[
            {
               "x":-2,
               "y":-2
            },
            {
               "x":-3,
               "y":-1
            },
            {
               "x":-4,
               "y":0
            },
            {
               "x":-5,
               "y":2
            },
            {
               "x":-5,
               "y":-1
            },
            {
               "x":-5,
               "y":1
            },
            {
               "x":-3,
               "y":1
            },
            {
               "x":-4,
               "y":2
            },
            {
               "x":-5,
               "y":3
            },
            {
               "x":-3,
               "y":3
            }
         ]
      },
      "powerSpawn":{
         "pos":[
            {
               "x":-2,
               "y":0
            }
         ]
      },
      "factory":{
         "pos":[
            {
               "x":0,
               "y":-1
            }
         ]
      },
      "container":{
         "pos":[
            {
               "x":-4,
               "y":1
            },
            {
               "x":-4,
               "y":3
            },
            {
               "x":-4,
               "y":-1
            }
         ]
      },
      "nuker":{
         "pos":[
            {
               "x":-2,
               "y":2
            }
         ]
      },
      "observer":{
         "pos":[
            {
               "x":1,
               "y":3
            }
         ]
      },
      "extension":{
         "pos":[
            {
               "x":-4,
               "y":-2
            },
            {
               "x":-4,
               "y":-3
            },
            {
               "x":-5,
               "y":-3
            },
            {
               "x":-5,
               "y":-2
            },
            {
               "x":-5,
               "y":-4
            },
            {
               "x":-3,
               "y":-4
            },
            {
               "x":-2,
               "y":-5
            },
            {
               "x":-3,
               "y":-5
            },
            {
               "x":-4,
               "y":-5
            },
            {
               "x":-1,
               "y":-5
            },
            {
               "x":-1,
               "y":-4
            },
            {
               "x":0,
               "y":-4
            },
            {
               "x":1,
               "y":-5
            },
            {
               "x":2,
               "y":-5
            },
            {
               "x":3,
               "y":-5
            },
            {
               "x":4,
               "y":-5
            },
            {
               "x":5,
               "y":-1
            },
            {
               "x":5,
               "y":-4
            },
            {
               "x":5,
               "y":-3
            },
            {
               "x":4,
               "y":-3
            },
            {
               "x":4,
               "y":-2
            },
            {
               "x":5,
               "y":-2
            },
            {
               "x":3,
               "y":-1
            },
            {
               "x":3,
               "y":-2
            },
            {
               "x":3,
               "y":1
            },
            {
               "x":4,
               "y":0
            },
            {
               "x":5,
               "y":2
            },
            {
               "x":5,
               "y":1
            },
            {
               "x":5,
               "y":3
            },
            {
               "x":4,
               "y":3
            },
            {
               "x":4,
               "y":2
            },
            {
               "x":5,
               "y":4
            },
            {
               "x":4,
               "y":5
            },
            {
               "x":3,
               "y":5
            },
            {
               "x":2,
               "y":5
            },
            {
               "x":1,
               "y":5
            },
            {
               "x":3,
               "y":4
            },
            {
               "x":2,
               "y":4
            },
            {
               "x":-5,
               "y":4
            },
            {
               "x":-4,
               "y":5
            },
            {
               "x":-2,
               "y":5
            },
            {
               "x":-1,
               "y":5
            },
            {
               "x":-2,
               "y":4
            },
            {
               "x":-3,
               "y":5
            },
            {
               "x":-3,
               "y":4
            },
            {
               "x":-2,
               "y":3
            },
            {
               "x":0,
               "y":4
            },
            {
               "x":1,
               "y":-3
            },
            {
               "x":2,
               "y":-3
            },
            {
               "x":2,
               "y":-4
            },
            {
               "x":3,
               "y":-4
            },
            {
               "x":-1,
               "y":3
            }
         ]
      },
      "road":{
         "pos":[
            {
               "x":-5,
               "y":-5
            },
            {
               "x":-4,
               "y":-4
            },
            {
               "x":-3,
               "y":-3
            },
            {
               "x":-3,
               "y":-2
            },
            {
               "x":-4,
               "y":-1
            },
            {
               "x":-5,
               "y":0
            },
            {
               "x":-4,
               "y":1
            },
            {
               "x":-3,
               "y":0
            },
            {
               "x":-2,
               "y":1
            },
            {
               "x":-1,
               "y":1
            },
            {
               "x":-1,
               "y":2
            },
            {
               "x":0,
               "y":3
            },
            {
               "x":-1,
               "y":4
            },
            {
               "x":0,
               "y":5
            },
            {
               "x":1,
               "y":4
            },
            {
               "x":2,
               "y":3
            },
            {
               "x":3,
               "y":3
            },
            {
               "x":3,
               "y":2
            },
            {
               "x":4,
               "y":4
            },
            {
               "x":5,
               "y":5
            },
            {
               "x":4,
               "y":1
            },
            {
               "x":3,
               "y":0
            },
            {
               "x":2,
               "y":-1
            },
            {
               "x":1,
               "y":-2
            },
            {
               "x":0,
               "y":-3
            },
            {
               "x":-1,
               "y":-3
            },
            {
               "x":-2,
               "y":-3
            },
            {
               "x":-2,
               "y":-4
            },
            {
               "x":2,
               "y":-2
            },
            {
               "x":1,
               "y":-1
            },
            {
               "x":-3,
               "y":2
            },
            {
               "x":-4,
               "y":3
            },
            {
               "x":-4,
               "y":4
            },
            {
               "x":-5,
               "y":5
            },
            {
               "x":3,
               "y":-3
            },
            {
               "x":4,
               "y":-4
            },
            {
               "x":5,
               "y":-5
            },
            {
               "x":0,
               "y":-5
            },
            {
               "x":1,
               "y":-4
            },
            {
               "x":5,
               "y":0
            },
            {
               "x":4,
               "y":-1
            }
         ]
      },
      "rampart":{
         "pos":[
            {
               "x":-5,
               "y":-1
            },
            {
               "x":-4,
               "y":0
            },
            {
               "x":-3,
               "y":1
            },
            {
               "x":-3,
               "y":-1
            },
            {
               "x":-2,
               "y":-2
            },
            {
               "x":-5,
               "y":1
            },
            {
               "x":-5,
               "y":2
            },
            {
               "x":-4,
               "y":2
            },
            {
               "x":-5,
               "y":3
            },
            {
               "x":-3,
               "y":3
            },
            {
               "x":-2,
               "y":2
            },
            {
               "x":-1,
               "y":-2
            },
            {
               "x":0,
               "y":-2
            },
            {
               "x":0,
               "y":-1
            },
            {
               "x":0,
               "y":0
            },
            {
               "x":-1,
               "y":0
            },
            {
               "x":-2,
               "y":0
            },
            {
               "x":-2,
               "y":-1
            },
            {
               "x":-1,
               "y":-1
            },
            {
               "x":0,
               "y":1
            },
            {
               "x":0,
               "y":2
            },
            {
               "x":1,
               "y":2
            },
            {
               "x":2,
               "y":1
            },
            {
               "x":2,
               "y":0
            },
            {
               "x":1,
               "y":0
            },
            {
               "x":1,
               "y":1
            },
            {
               "x":1,
               "y":3
            }
         ]
      }
   }
}

var basebuild = {
     run: function(roomname, storage_xpos, storage_ypos)
     {
         var goalroom = Game.rooms[roomname];
         var terrain = goalroom.getTerrain();
         for(var i = 0; i < roads.length; i++)
         {
            
                 if(terrain.get(storage_xpos + roads[i][0], storage_ypos + roads[i][1]) != 1)
                 {
                     goalroom.createConstructionSite(storage_xpos + roads[i][0], storage_ypos + roads[i][1], STRUCTURE_ROAD);
                 }
             
           
         }
       
         ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
         if(goalroom.storage == undefined)
         {
             goalroom.createConstructionSite(storage_xpos, storage_ypos, STRUCTURE_STORAGE);
         }
   
         ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
         
               
         ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     }
 }
 module.exports = basebuild;